export const GET_ALL = 'GET_ALL'
export const GET_ONE = 'GET_ONE'
export const DELETE = 'DELETE'
export const UPDATE = 'UPDATE'
export const UPDATE_CURRENT = 'UPDATE_CURRENT'
export const CREATE = 'CREATE'
